title: Vedant Chandra
logo: /vedantchandra.github.io/assets/headshot.jpg
description: Department of Physics and Astronomy, Johns Hopkins University
theme: jekyll-theme-minimal
baseurl: /vedantchandra.github.io
