title: Vedant Chandra
logo: {{site.baseurl}}/assets/headshot.jpg
description: Department of Physics and Astronomy, Johns Hopkins University
theme: jekyll-theme-minimal
baseurl: /vedantchandra.github.io
